services:
  babylonjspopover:
    container_name: 'babylonjspopover'
    image: node:21-alpine3.18
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'tail -f /dev/null'

